#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/train
#    username: postgres
#    password: Victor
#
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        ddl_auto: create

spring.datasource.url=jdbc:postgresql://localhost:5432/train
spring.datasource.username=postgres
spring.datasource.password=Victor

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.hibernate.ddl_auto=create-drop
spring.jpa.show-sql=true