spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/train
    username: postgres
    password: Victor

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
        ddl_auto: create-drop